models:
  - name:  faster_rcnn_resnet50_coco
    launchers:
      - framework: dlsdk
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[1024, 1024, 1]]

    datasets:
      - name: COCO2017_detection_91cl_bkgr

        preprocessing:
          - type: resize
            size: 1024

        postprocessing:
          - type: faster_rcnn_postprocessing_resize
            size: 1024

        metrics:
          - type: coco_precision
            reference: 0.3537
          - type: coco_orig_precision
            reference: 0.3372
