models:
- name: googlenet-v4
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: ImageNet2012
    preprocessing:
    - type: resize
      size: 320
    - type: crop
      size: 299
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
      reference: 0.799
    - name: accuracy@top5
      type: accuracy
      top_k: 5
      reference: 0.94992
