models:
- name: ssd-mobilenet-cf
  launchers:
  - framework: caffe
    model: public/mobilenet-ssd/mobilenet-ssd.prototxt
    weights: public/mobilenet-ssd/mobilenet-ssd.caffemodel
    adapter: ssd
  datasets:
  - name: VOC2012
    preprocessing:
    - type: resize
      size: 300
    - type: normalization
      mean: 127.5
      std: 127.5
    postprocessing:
    - type: resize_prediction_boxes
    metrics:
    - type: map
      integral: 11point
      ignore_difficult: true
      presenter: print_scalar
- name: ssd-mobilenet
  launchers:
  - framework: dlsdk
    tags:
    - INT8
    adapter: ssd
  datasets:
  - name: VOC2012
    preprocessing:
    - type: resize
      size: 300
    postprocessing:
    - type: resize_prediction_boxes
    metrics:
    - type: map
      integral: 11point
      ignore_difficult: true
      presenter: print_scalar
