models:
- name: resnet-50-cf
  launchers:
  - framework: caffe
    model: public/resnet-50/resnet-50.prototxt
    weights: public/resnet-50/resnet-50.caffemodel
    adapter: classification
  datasets:
  - name: imagenet_1000_classes
    preprocessing:
    - type: resize
      size: 256
      aspect_ratio_scale: greater
    - type: crop
      size: 224
    - type: normalization
      mean: 104, 117, 123
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
    - name: acciracy@top5
      type: accuracy
      top_k: 5
- name: resnet-50
  launchers:
  - framework: dlsdk
    tags:
    - INT8
    adapter: classification
  datasets:
  - name: imagenet_1000_classes
    preprocessing:
    - type: resize
      size: 256
      aspect_ratio_scale: greater
    - type: crop
      size: 224
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
    - name: acciracy@top5
      type: accuracy
      top_k: 5
