models:
- name: se-resnet-50
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: ImageNet2015
    preprocessing:
    - type: resize
      size: 256
    - type: crop
      size: 224
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
      reference: 0.77596
    - name: accuracy@top5
      type: accuracy
      top_k: 5
      reference: 0.9385
