models:
    - name: cgan
      launchers:
          - framework: dlsdk
            adapter: image_processing
            inputs:
                - name: "0"
                  type: INPUT
                  value: "z_100.*"
                - name: "input.1"
                  type: INPUT
                  value: "labels.*"
      datasets:
          - name: CGAN_dataset
            metrics:
                - type: mae
                  presenter: print_vector
                  reference:
                    mean: 45.30956
                    std: 13.461788
