models:
  - name: CTPN-tf

    launchers:
      - framework: tf
        device: CPU
        model: ctpn.pb
        adapter:
          type: ctpn_text_detection
          cls_prob_out: 'Reshape_2'
          bbox_pred_out: 'rpn_bbox_pred/Reshape_1'

        output_names:
          - 'Reshape_2'
          - 'rpn_bbox_pred/Reshape_1'

    datasets:
      - name: ICDAR2013_detection
        data_source: icdar13_DET
        annotation_conversion:
          converter: icdar_detection
          data_dir: icdar13_DET/gt

        preprocessing:
        - type: resize
          dst_width: 1200
          dst_height: 600
          aspect_ratio_scale: ctpn_keep_aspect_ratio
        - type: normalization
          mean: 102.9801, 115.9465, 122.7717
        - type: resize
          dst_width: 1000
          dst_height: 600
          aspect_ratio_scale: ctpn_keep_aspect_ratio

        postprocessing:
          - type: cast_to_int
            round_policy: lower

        metrics:
        - type: focused_text_precision
          name: precision
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4

        - type: focused_text_recall
          name: recall
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4

        - type: focused_text_hmean
          name: hmean
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4

  - name: CTPN

    launchers:
      - framework: dlsdk
        device: CPU
        tf_model: ctpn.pb
        adapter:
          type: ctpn_text_detection
          cls_prob_out: 'Reshape_2/Transpose'
          bbox_pred_out: 'rpn_bbox_pred/Reshape_1/Transpose'
        allow_reshape_input: True
        mo_params:
          mean_values: '(102.9801, 115.9465, 122.7717)'
          input_shape: '(1,600,1000,3)'
        mo_flags:
          - keep_shape_ops


    datasets:
      - name: ICDAR2013_detection
        data_source: icdar13_DET
        annotation_conversion:
          converter: icdar_detection
          data_dir: icdar13_DET/gt

        preprocessing:
        - type: resize
          dst_width: 1200
          dst_height: 600
          aspect_ratio_scale: ctpn_keep_aspect_ratio

        - type: resize
          dst_width: 1000
          dst_height: 600
          aspect_ratio_scale: ctpn_keep_aspect_ratio

        postprocessing:
          - type: cast_to_int
            round_policy: lower

        metrics:
        - type: focused_text_precision
          name: precision
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4

        - type: focused_text_recall
          name: recall
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4

        - type: focused_text_hmean
          name: hmean
          ignore_difficult: True
          area_recall_constrain: 0.8
          area_precision_constrain: 0.4
