models:
  - name: deblurgan-v2

    launchers:
      - framework: dlsdk
        adapter:
          type: image_processing
          reverse_channels: True

    datasets:
      - name: GoPro
        preprocessing:
          - type: padding
            dst_height: 736
            dst_width: 1312
            use_numpy: True
            pad_type: right_bottom
        postprocessing:
          - type: corner_crop_image
            apply_to: prediction
        metrics:
          - type: psnr
            scale_border: 0
            presenter: print_vector
            reference:
              mean: 28.25
          - type: ssim
            presenter: print_vector
            reference:
              mean: 0.97
