models:
  - name: deeplabv3_mnv2_cityscapes
    launchers:
      - framework: dlsdk
        adapter: segmentation

    datasets:
      - name: Cityscapes_19cl
        preprocessing:
          - type: resize
            size: 1024
        postprocessing:
          - type: resize_segmentation_mask
            to_dst_image_size: True
            apply_to: annotation
          - type: crop_or_pad
            size: 1024
        metrics:
          - type: mean_iou
            use_argmax: false
            presenter: print_scalar
            ignore_label: 19
            reference: 0.609
