models:
  - name: densenet-161

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        model:   public/densenet-161/densenet-161.prototxt
        weights: public/densenet-161/densenet-161.caffemodel
        backend: OCV
        inputs:
            - name: "data"
              type: INPUT
              shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: ImageNet2012
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 224

          - type: normalization
            mean: 103.94, 116.78, 123.68
            std:  58.8235294

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
