models:
  - name: east_resnet_v1_50
    launchers:
      - framework: dlsdk
        allow_reshape_input: True
        adapter:
          type: east_text_detection
          score_map_out: feature_fusion/Conv_7/Sigmoid
          geometry_map_out: feature_fusion/concat_3

    datasets:
    - name: ICDAR2015_detection
      preprocessing:
      - type: resize
        dst_height: 2400
        dst_width: 32
        aspect_ratio_scale: east_keep_aspect_ratio
      - type: bgr_to_rgb

      metrics:
      - type: incidental_text_hmean
        name: f-measure
        ignore_difficult: True
        reference: 0.7435
