models:
  - name: efficientnet-b3

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        reader: pillow_imread

        preprocessing:
          - type: resize
            size: 332
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
          - type: crop
            use_pillow: True
            size: 300
          - type: rgb_to_bgr

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.81516
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.95672
