models:
  - name: efficientnet-v2-b0

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        reader: pillow_imread

        preprocessing:
          - type: rgb_to_bgr

          - type: resize
            size: 256
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC

          - type: crop
            use_pillow: True
            size: 224

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.78358
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.94024
