models:
  - name: efficientnet-b0

    launchers:
      - framework: tf
        device: CPU
        model: efficientnet-b0/model.ckpt.meta
        adapter: classification
        output_names:
          - logits
        inputs:
           - name: IteratorGetNext
             type: INPUT


    datasets:
      - name: ImageNet2012
        data_source: ImageNet
        annotation: imagenet1000.pickle
        reader: pillow_imread
        subsample_size: 10

        preprocessing:
        - type: crop
          central_fraction: 0.875
          use_pillow: True
        - type: resize
          size: 224
          use_pillow: True
          interpolation: BICUBIC

        metrics:
          - name: accuracy @ top1
            type: accuracy
            top_k: 1

          - name: accuracy @ top5
            type: accuracy
            top_k: 5
