models:
  - name: facenet

    launchers:
      - framework: dlsdk
        adapter:
          type: reid
          joining_method: concatenation

    datasets:
      - name: LFW_MTCNN_aligned

        preprocessing:
          - type: resize
            size: 160

        metrics:
          - type: pairwise_accuracy_subsets
            min_score: best_train_threshold
            reference: 0.978619
