models:
  - name: fastseg-small
    launchers:
      - framework: dlsdk
        adapter:
          type: segmentation
          make_argmax: true

    datasets:
      - name: Cityscapes_19cl
        metrics:
          - type: mean_iou
            use_argmax: false
            presenter: print_scalar
            reference: 0.6715
