models:
  - name: faster-rcnn-inception-resnet-v2-atrous-lowproposals-oid
    launchers:
      - framework: dlsdk
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[600, 1024, 1]]

    datasets:
      - name: OpenImagesDataset_v4

        preprocessing:
          - type: resize
            aspect_ratio_scale: fit_to_window
            dst_width: 1024
            dst_height: 600
          - type: padding
            dst_width: 1024
            dst_height: 600
            pad_type: right_bottom

        postprocessing:
          - type: faster_rcnn_postprocessing_resize
            dst_height: 600
            dst_width: 1024

        metrics:
          - type: map
