models:
  - name: hbonet-0.8

    launchers:
      - framework: dlsdk
        adapter:
          type: classification
          classification_output: output

    datasets:
      - name: ImageNet2012
        reader: opencv_imread

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
            interpolation: BILINEAR
            use_pillow: True

          - type: crop
            size: 224

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.71254
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.89754
