models:
  - name: Inception-ResNet-v2

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   classification/inception-resnet/v2/caffe/inception-resnet-v2.prototxt
        weights: classification/inception-resnet/v2/caffe/inception-resnet-v2.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 299, 299
        adapter: classification

#      - framework: opencv
#        device: GPU
#        tags:
#          - FP32
#        model:   classification/inception-resnet/v2/caffe/inception-resnet-v2.prototxt
#        weights: classification/inception-resnet/v2/caffe/inception-resnet-v2.caffemodel
#        backend: OCV
#        inputs:
#          - name: "data"
#            type: INPUT
#            shape: 3, 299, 299
#        adapter: classification

#      - framework: opencv
#        device: GPU
#        tags:
#          - FP16
#        model:   classification/inception-resnet/v2/caffe/inception-resnet-v2.prototxt
#        weights: classification/inception-resnet/v2/caffe/inception-resnet-v2.caffemodel
#        backend: OCV
#        inputs:
#          - name: "data"
#            type: INPUT
#            shape: 3, 299, 299
#        adapter: classification

    datasets:
      - name: ImageNet2012
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 320

          - type: crop
            size: 299

          - type: normalization
            mean: 127.5
            std:  127.5

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1

          - name: accuracy@top5
            type: accuracy
            top_k: 5
