models:
  - name: inceptionv3-int8-onnx-0001

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        data_source: ImageNet
        reader: pillow_imread

        preprocessing:
        - type: resize
          size: 341
          aspect_ratio_scale: greater
          use_pillow: True
          interpolation: BILINEAR
        - type: crop
          size: 299
          use_pillow: True
        - type: bgr_to_rgb

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.78336
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.93968
