models:
  - name: instance-segmentation-security-0228

    launchers:
      - framework: dlsdk
        adapter:
          type: mask_rcnn
          classes_out: labels
          boxes_out: boxes
          raw_masks_out: masks

    datasets:
      - name: COCO2017_mask_rcnn_80cl

        preprocessing:
          - type: resize
            size: 608

        metrics:
          - name: AP@masks
            type: coco_orig_segm_precision
            reference: 0.339

          - name: AP@boxes
            type: coco_orig_precision
            reference: 0.3885
