models:
  - name: lraspp-mobilenet-v3-large
    launchers:
      - framework: dlsdk
        adapter:
          type: segmentation
          make_argmax: true

    datasets:
      - name: COCO2017_segm_with_VOC_labels
        preprocessing:
            - type: resize
              size: 520
        postprocessing:
            - type: resize_segmentation_mask
              apply_to: annotation
              size: 520
        metrics:
            - type: mean_iou
              use_argmax: false
              presenter: print_scalar
              reference: 0.581631
            - type: segmentation_accuracy
              use_argmax: false
              presenter: print_scalar
              reference: 0.902525
