models:
  - name: mobilenet-v3-small-1.0-224
    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        preprocessing:
        - type: resize
          size: 256
          aspect_ratio_scale: greater
          use_pillow: true
          interpolation: BILINEAR
        - type: crop
          use_pillow: true
          size: 224

        metrics:
          - name: accuracy @ top1
            type: accuracy
            top_k: 1
            reference: 0.671

          - name: accuracy @ top5
            type: accuracy
            top_k: 5
            reference: 0.8638
