models:
- name: mobilenet-v2-1.4-224
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: ImageNet2012_bkgr
    preprocessing:
    - type: crop
      central_fraction: 0.875
    - type: resize
      size: 224
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
      reference: 0.7409
    - name: accuracy@top5
      type: accuracy
      top_k: 5
      reference: 0.9197
