models:
  - name: mobilebert
    launchers:
      - framework: dlsdk
        adapter:
          type: bert_question_answering
          start_token_logits_output: "11507"
          end_token_logits_output: "11508"
        inputs:
          - name: "result.1"
            type: INPUT
            value: "input_ids"
          - name: "result.2"
            type: INPUT
            value: 'input_mask'
          - name: 'result.3'
            type: INPUT
            value: 'segment_ids'

    datasets:
      - name: SQUAD_v1_1_bert_msl384_mql64_ds128_lowercase
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
            - input_mask
            - segment_ids
        postprocessing:
          - type: extract_answers_tokens
            max_answer: 30
            n_best_size: 20
        metrics:
          - name: 'F1'
            type: 'f1'
          - name: 'EM'
            type: 'exact_match'
