models:
  - name: person-detection-0202

    launchers:
      - framework: dlsdk
        adapter: ssd

    datasets:
      - name: Crossroad_extra_untagged_person_no_bkgr
        preprocessing:
          - type: resize
            dst_width: 512
            dst_height: 512
        postprocessing:
          - type: resize_prediction_boxes
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: coco_orig_precision
            include_boundaries: false
            reference: 0.322
