models:
  - name: person-detection-0101

    launchers:
      - framework: dlsdk
        adapter: ssd

    datasets:
      - name: DatatangStreetSubway

        preprocessing:
          - type: resize
            dst_width: 384
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: annotation
            height_range: 100
            aspect_ratio: 0.666, 5
            is_empty: True
            min_visibility: partially occluded
          - type: filter
            apply_to: prediction
            height_range: 100
            is_empty: True
            aspect_ratio: 0.666, 5

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: True
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
            reference: 0.8814
