models:
  - name: person-vehicle-bike-detection-2002

    launchers:
      - framework: dlsdk
        adapter: ssd

    datasets:
      - name: Crossroad_extra_untagged_no_bkgr
        preprocessing:
          - type: resize
            dst_width: 512
            dst_height: 512
        postprocessing:
          - type: resize_prediction_boxes
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: coco_orig_precision
            include_boundaries: false
            reference: 0.2459
