models:
  - name: refinedet-resnet-101
    launchers:
      - framework: dlsdk
        adapter: ssd
    datasets:
      - name: COCO2017_detection_80cl_bkgr
        preprocessing:
          - type: resize
            size: 320
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
            reference: 0.506305
          - type: coco_precision
            max_detections: 100
            reference: 0.313944
