models:
  - name: resnet-50

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/resnet-50/resnet-50.prototxt
        weights: public/resnet-50/resnet-50.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        backend: OCV
        model:   public/resnet-50/resnet-50.prototxt
        weights: public/resnet-50/resnet-50.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        backend: OCV
        model:   public/resnet-50/resnet-50.prototxt
        weights: public/resnet-50/resnet-50.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 224, 224
        adapter: classification

    datasets:
      - name: ImageNet2012
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater

          - type: crop
            size: 224

          - type: normalization
            mean: 104, 117, 123

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
