models:
  - name: resnet-v2-152
    launchers:
      - framework: dlsdk
        adapter: classification
    datasets:
      - name: ImageNet2012_bkgr
        preprocessing:
          - type: resize
            size: 320
          - type: crop
            size: 299
        metrics:
          - name: top1
            type: accuracy
            top_k: 1
            reference: 0.77506
          - name: top5
            type: accuracy
            top_k: 5
            reference: 0.93832
