models:
  - name: retinaface-resnet50
    launchers:
      - framework: dlsdk
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
          landmarks_outputs:
            - face_rpn_landmark_pred_stride32
            - face_rpn_landmark_pred_stride16
            - face_rpn_landmark_pred_stride8
    datasets:
      - name: WiderFace_label_1
        preprocessing:
          - type: resize
            size: 640
        postprocessing:
          - type: cast_to_int
          - type: clip_boxes
            size: 1024
            apply_to: annotation
          - type: filter
            apply_to: annotation
            height_range: 64, 1024
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
            reference: 0.873

      - name: VGGFace2
        annotation: vggfaces2_1000.pickle
        subsample_size: 1000
        preprocessing:
          - type: resize
            size: 640
        metrics:
          - type: per_point_normed_error
            presenter: print_vector
            reference:
              point_0_normed_error: 0.090393
              point_1_normed_error: 0.093413
              point_2_normed_error: 0.090516
              point_3_normed_error: 0.086353
              point_4_normed_error: 0.104622
              mean: 0.09306
          - type: normed_error
            reference: 0.09306
