models:
  - name:  rfcn-resnet101-coco
    launchers:
      - framework: dlsdk
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[600, 600, 1]]

    datasets:
      - name: COCO2017_detection_91cl_bkgr

        preprocessing:
            -   type: resize
                aspect_ratio_scale: fit_to_window
                dst_height: 600
                dst_width: 600
            -   type: padding
                dst_height: 600
                dst_width: 600
                pad_type: right_bottom

        postprocessing:
            -   type: faster_rcnn_postprocessing_resize
                dst_height: 600
                dst_width: 600

        metrics:
          - type: coco_precision
            max_detections: 100
            reference: 0.284
