models:
- name: road-segmentation-adas-0001
  launchers:
  - framework: dlsdk
    adapter: segmentation
  datasets:
  - name: Mighty

    preprocessing:
    - type: resize
      dst_height: 512
      dst_width: 896
    postprocessing:
    - type: resize_segmentation_mask
      apply_to: annotation
      dst_height: 512
      dst_width: 896
    metrics:
    - type: mean_iou
      presenter: print_vector
      reference:
        BG: 0.986
        curbs: 0.727
        marks: 0.707
        mean: 0.844
        road: 0.954
    - type: mean_accuracy
      presenter: print_vector
      reference:
        BG: 0.994
        curbs: 0.825
        marks: 0.803
        mean: 0.899
        road: 0.974
