models:
    - name: sbert-base-mean-tokens
      launchers:
          - framework: dlsdk
            adapter:
                type: reid
                target_out: sentence_embedding
            inputs:
                -   name: "input_ids"
                    type: INPUT
                    value: "input_ids"
                -   name: "attention_mask"
                    type: INPUT
                    value: 'input_mask'
                -   name: 'token_type_ids'
                    type: INPUT
                    value: 'segment_ids'
      datasets:
          - name: STS-B_test_sbert_padded
            metrics:
                - type: spearman_correlation_coef
                  similarity_distance: cosine
                  name: spearman@cosine
                  reference: 0.850728
                - type: pearson_correlation_coef
                  similarity_distance: cosine
                  name: pearson@cosine
                  reference: 0.842079
