models:
- name: single-human-pose-estimation-0001
  launchers:
  - framework: dlsdk
    adapter:
      type: single_human_pose_estimation
  datasets:
  - name: COCO2017_keypoints_single_instance
    preprocessing:
    - type: transformed_crop_with_auto_scale
      dst_height: 384
      dst_width: 288
      stride: 8
    metrics:
    - name: AP
      type: coco_orig_keypoints_precision
      reference: 0.6904
