models:
  - name: ssd300

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        backend: OCV
        model:   object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/deploy.prototxt
        weights: object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

      - framework: opencv
        device: GPU
        tags:
          - FP32
        backend: OCV
        model:   object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/deploy.prototxt
        weights: object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

      - framework: opencv
        device: GPU
        tags:
          - FP16
        backend: OCV
        model:   object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/deploy.prototxt
        weights: object_detection/common/ssd/300/caffe/models/VGGNet/VOC0712Plus/SSD_300x300_ft/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 300, 300
        adapter: ssd

    datasets:
      - name: VOC2007_detection

        preprocessing:
          - type: resize
            size: 300

          - type: normalization
            mean: 104, 117, 123

        postprocessing:
          - type: resize_prediction_boxes

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: False
