models:
- name: ssdlite_mobilenet_v2
  launchers:
  - framework: dlsdk
    adapter: ssd
  datasets:
  - name: COCO2017_detection_91cl_bkgr
    preprocessing:
    - type: resize
      size: 300
    postprocessing:
    - type: resize_prediction_boxes
    metrics:
    - type: coco_precision
      reference: 0.242946
    - type: coco_orig_precision
      reference: 0.241498
