models:
- name: text-image-super-resolution-0001
  launchers:
  - framework: dlsdk
    adapter:
      type: super_resolution
  datasets:
  - name: ICDAR_super_resolution

    preprocessing:
    - type: bgr_to_gray
    metrics:
    - type: psnr
      scale_border: 4
      presenter: print_vector
      reference:
        mean: 20.318
        std: 0.73
