models:
  - name: unet-camvid-int8-onnx-0001

    launchers:
      - framework: dlsdk
        adapter: segmentation

    datasets:
      - name: CamVid_12cl
        reader: pillow_imread

        preprocessing:
          - type: resize
            dst_height: 368
            dst_width: 480
            use_pillow: True
            interpolation: BILINEAR
          - type: bgr_to_rgb

        postprocessing:
          - type: resize_segmentation_mask
            apply_to: annotation
            dst_height: 368
            dst_width: 480

        metrics:
          - type: mean_iou
            use_argmax: True
            presenter: print_vector
            reference:
             Bicyclist: 0.722486
             Building: 0.697305
             Car: 0.781317
             Fence: 0.632187
             Pavement: 0.842669
             Pedestrian: 0.346797
             Pole: 0.172106
             Road: 0.960562
             SignSymbol: 0.46243
             Sky: 0.319166
             Tree: 0.897157
             Unlabelled: 0
             mean: 0.569515
