models:
  - name: yolo-v3

    launchers:
      - framework: dlsdk
        adapter:
            type: yolo_v3
            anchors: "10,13,  16,30,  33,23,  30,61,  62,45,  59,119,  116,90,  156,198,  373,326"
            num: 9
            coords: 4
            classes: 80
            anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
            outputs:
              - detector/yolo-v3/Conv_6/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_14/BiasAdd/YoloRegion
              - detector/yolo-v3/Conv_22/BiasAdd/YoloRegion

    datasets:
      - name: COCO2017_detection_80cl

        preprocessing:
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
            reference: 0.6227
          - type: coco_precision
            max_detections: 100
            threshold: 0.5
            reference: 0.677
