models:
  - name: yolox-tiny
    launchers:
      - framework: dlsdk
        adapter: yolox
    datasets:
      - name: COCO2017_detection_80cl

        preprocessing:
          - type: resize
            aspect_ratio_scale: fit_to_window
            size: 416
          - type: padding
            pad_type: right_bottom
            pad_value: '114, 114, 114'
        postprocessing:
          - type: resize_prediction_boxes
            rescale: True
          - type: nms
            overlap: 0.65
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
            reference: 0.4785
          - name: AP@0.5
            type: coco_precision
            max_detections: 100
            threshold: 0.5
            reference: 0.5256
          - name: AP@0.5:0.05:95
            type: coco_precision
            max_detections: 100
            threshold: '0.5:0.05:0.95'
            reference: 0.3182
