evaluations:
  - name: action-recognition-0001-encoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          model: action-recognition-0001-encoder/FP32/action-recognition-0001-encoder.xml
          weights: action-recognition-0001-encoder/FP32/action-recognition-0001-encoder.bin


        decoder:
          model: action-recognition-0001-decoder/FP32/action-recognition-0001-decoder.xml
          weights: action-recognition-0001-decoder/FP32/action-recognition-0001-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP32

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F
            - FP16
          bitstream: 2019R2_PL1_FP16_AlexNet_GoogleNet_InceptionV1_SqueezeNet_TinyYolo_VGG_Generic.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F
            - FP11
          bitstream: 2019R2_PL1_FP11_AlexNet_GoogleNet_SqueezeNet_Generic.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F-SG2
            - FP16
          bitstream: 2019R2_PL2_FP16_MobileNet_Clamp.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F-SG2
            - FP11
          bitstream: 2019R2_PL2_FP11_ResNet_VGG.aocx

      datasets:
      - name: kinetics-400
        data_source: kinetics/frames_val
        annotation: kinetics_action_recognition.pickle
        dataset_meta: kinetics_action_recognition.json
        subsample_size: 2000

        preprocessing:
        - type: resize
          size: 224
          aspect_ratio_scale: fit_to_window
        - type: crop
          size: 224

        metrics:
        - type: clip_accuracy
          presenter: print_vector

  - name: action-recognition-0001-encoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          model: action-recognition-0001-encoder/FP16/action-recognition-0001-encoder.xml
          weights: action-recognition-0001-encoder/FP16/action-recognition-0001-encoder.bin

        decoder:
          model: action-recognition-0001-decoder/FP16/action-recognition-0001-decoder.xml
          weights: action-recognition-0001-decoder/FP16/action-recognition-0001-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
      - name: kinetics-400
        data_source: kinetics/frames_val
        annotation: kinetics_action_recognition.pickle
        dataset_meta: kinetics_action_recognition.json
        subsample_size: 2000

        preprocessing:
        - type: resize
          size: 224
          aspect_ratio_scale: fit_to_window
        - type: crop
          size: 224

        metrics:
        - type: clip_accuracy
          presenter: print_vector
