models:
  - name: albert-base-v2

    launchers:
      - framework: dlsdk
        adapter:
          type: reid
          keep_shape: True
          target_out: last_hidden_state
        inputs:
          - name: "input_ids"
            type: INPUT
            value: "input_ids"
          - name: "attention_mask"
            type: INPUT
            value: "input_mask"
          - name: "token_type_ids"
            type: INPUT
            value: "segment_ids"

    datasets:
      - name: STS-B_test_albert_padded

        postprocessing:
          - type: sentence_similarity_pooling

        metrics:
          - name: spearman@cosine
            type: spearman_correlation_coef
            similarity_distance: cosine

          - name: pearson@cosine
            type: pearson_correlation_coef
            similarity_distance: cosine
