models:
  - name: bert-base-chinese-xnli-zh-onnx
    launchers:
      - framework: dlsdk
        adapter:
            type: bert_classification
            num_classes: 3
        inputs:
          - name: "0"
            type: INPUT
            value: "input_ids"
          - name: "1"
            type: INPUT
            value: 'input_mask'
          - name: '2'
            type: INPUT
            value: 'segment_ids'

    datasets:
      - name: xnli
        data_source: XNLI-1.0
        annotation_conversion:
            converter: xnli
            annotation_file: XNLI-1.0/xnli.test.tsv
            vocab_file: bert-base-chinese-xnli-zh-onnx/vocab.txt
            language_filter: zh
            max_seq_length: 128
        reader:
            type: annotation_features_extractor
            features:
                - input_ids
                - input_mask
                - segment_ids
        metrics:
            - type: accuracy
