models:
  - name: bert-base-uncased-mrpc
    launchers:
      - framework: dlsdk
        adapter:
          type: bert_classification
          num_classes: 2
        inputs:
          - name: "input_ids"
            type: INPUT
            value: "input_ids"
          - name: "input_mask"
            type: INPUT
            value: 'input_mask'
          - name: 'segment_ids'
            type: INPUT
            value: 'segment_ids'
    datasets:
      - name: GLUE_MRPC_bert_uncased
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
            - input_mask
            - segment_ids
        metrics:
          - type: accuracy
            reference: 0.857843
          - type: classification_f1-score
            pos_label: 1
            reference: 0.900344
