evaluations:
  - name: driver-action-recognition-adas-0002-encoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          model: driver-action-recognition-adas-0002-encoder/FP32/driver-action-recognition-adas-0002-encoder.xml
          weights: driver-action-recognition-adas-0002-encoder/FP32/driver-action-recognition-adas-0002-encoder.bin


        decoder:
          model: driver-action-recognition-adas-0002-decoder/FP32/driver-action-recognition-adas-0002-decoder.xml
          weights: driver-action-recognition-adas-0002-decoder/FP32/driver-action-recognition-adas-0002-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP32

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F
            - FP16
          bitstream: 2019R2_PL1_FP16_AlexNet_GoogleNet_InceptionV1_SqueezeNet_TinyYolo_VGG_Generic.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F
            - FP11
          bitstream: 2019R2_PL1_FP11_AlexNet_GoogleNet_SqueezeNet_Generic.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F-SG2
            - FP16
          bitstream: 2019R2_PL2_FP16_MobileNet_Clamp.aocx

        - framework: dlsdk
          device: HETERO:FPGA,CPU
          tags:
            - HDDL-F-SG2
            - FP11
          bitstream: 2019R2_PL2_FP11_ResNet_VGG.aocx

      datasets:
      - name: kelly_driver_recognition_dataset
        annotation: driver_action_recognition.pickle
        dataset_meta: driver_action_recognition.json
        data_source: icv_ar_val_kelly

        preprocessing:
        - type: resize
          size: 224
          aspect_ratio_scale: fit_to_window
        - type: crop
          size: 224

        metrics:
        - type: clip_accuracy

  - name: driver-action-recognition-adas-0002-encoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          model: driver-action-recognition-adas-0002-encoder/FP16/driver-action-recognition-adas-0002-encoder.xml
          weights: driver-action-recognition-adas-0002-encoder/FP16/driver-action-recognition-adas-0002-encoder.bin

        decoder:
          model: driver-action-recognition-adas-0002-decoder/FP16/driver-action-recognition-adas-0002-decoder.xml
          weights: driver-action-recognition-adas-0002-decoder/FP16/driver-action-recognition-adas-0002-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
      - name: kelly_driver_recognition_dataset
        annotation: driver_action_recognition.pickle
        dataset_meta: driver_action_recognition.json
        data_source: icv_ar_val_kelly

        preprocessing:
        - type: resize
          size: 224
          aspect_ratio_scale: fit_to_window
        - type: crop
          size: 224

        metrics:
        - type: clip_accuracy
          presenter: print_vector
