models:
- name: efficientnet-b5
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: ImageNet2012
    reader: pillow_imread
    preprocessing:
    - type: rgb_to_bgr
    - type: resize
      size: 488
      aspect_ratio_scale: greater
      use_pillow: true
      interpolation: BICUBIC
    - type: crop
      use_pillow: true
      size: 456
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
      reference: 0.8369
    - name: accuracy@top5
      type: accuracy
      top_k: 5
      reference: 0.9671
