models:
- name: face-recognition-resnet34-arcface
  launchers:
  - framework: dlsdk
    adapter: reid
  datasets:
  - name: LFW_bin
    metrics:
    - type: pairwise_accuracy_subsets
      reference: 0.9965
