models:
- name: face-reidentification-retail-0095
  launchers:
  - framework: dlsdk
    adapter: reid

  datasets:
  - name: LFW

    preprocessing:
    - type: point_alignment
      size: 400
    - type: resize
      size: 128
    metrics:
    - type: pairwise_accuracy_subsets
      reference: 0.9947
