models:
  - name: facenet-20180408-102900

    launchers:
      - framework: dlsdk
        adapter:
          type: reid
          joining_method: concatenation

    datasets:
      - name: LFW_MTCNN_aligned

        preprocessing:
          - type: flip
            mode: vertical
            merge_with_original: True
        metrics:
          - type: pairwise_accuracy_subsets
            min_score: best_train_threshold
            distance_method: 'cosine_distance'
            subtract_mean: True
            reference: 0.9914
