models:
  - name: hbonet-1.0

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        reader: opencv_imread

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
            interpolation: BILINEAR
            use_pillow: True

          - type: crop
            size: 224
        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.731
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.91
