models:
- name: instance-segmentation-security-0083
  launchers:
  - framework: dlsdk
    adapter:
      type: mask_rcnn
      classes_out: classes
      scores_out: scores
      boxes_out: boxes
      raw_masks_out: raw_masks
    inputs:
    - name: im_info
      type: IMAGE_INFO
  datasets:
  - name: COCO2017_mask_rcnn_80cl_bkgr
    data_source: MSCOCO/val2017

    preprocessing:
    - type: resize
      dst_width: 640
      dst_height: 480
      aspect_ratio_scale: fit_to_window
    - type: padding
      dst_width: 640
      dst_height: 480
      pad_type: right_bottom
      use_numpy: true
    metrics:
    - name: AP@masks
      type: coco_orig_segm_precision
      reference: 0.3556
    - name: AP@boxes
      type: coco_orig_precision
      reference: 0.4016
