models:
- name: mlp-mixer-b16-224-miil
  launchers:
    - framework: dlsdk
      adapter: classification
  datasets:
    - name: ImageNet2012
      reader: pillow_imread
      preprocessing:
        - type: resize
          size: 256
          interpolation: BILINEAR
          aspect_ratio_scale: greater
          use_pillow: True
        - type: crop
          size: 224
          use_pillow: True
        - type: rgb_to_bgr
      metrics:
        - name: accuracy@top1
          type: accuracy
          top_k: 1
          reference: 0.82308
        - name: accuracy@top5
          type: accuracy
          top_k: 5
          reference: 0.9572
