models:
  - name: mobilenet-yolo-v4-syg
    launchers:
      - framework: dlsdk
        adapter:
          type: yolo_v3
          classes: 4
          anchors: 12,16, 19,36, 40,28, 36,75, 76,55, 72,146, 142,110, 192,243, 459,401
          coords: 4
          num: 9
          anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
          threshold: 0.001
          outputs:
            - separable_conv2d_22/separable_conv2d/YoloRegion
            - separable_conv2d_30/separable_conv2d/YoloRegion
            - separable_conv2d_38/separable_conv2d/YoloRegion
    datasets:
      - name: SYGData0829
        preprocessing:
          - type: resize
            size: 416
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            remove_filtered: true
            apply_to: prediction
            min_confidence: 0.001
          - type: diou_nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter:  print_scalar
            reference: 0.8635
