models:
  - name: netvlad
    launchers:
      - framework: dlsdk
        adapter: reid
    datasets:
      - name: Pitts30k_val
        reader: pillow_imread

        preprocessing:
          - type: rgb_to_bgr
          - type: resize
            dst_height: 200
            dst_width: 300
        metrics:
          - type: localization_recall
            reference: 0.820321
