models:
  - name: nfnet-f6

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        reader: pillow_imread

        preprocessing:
          - type: resize
            size: 602
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
          - type: crop
            size: 576
            use_pillow: True
          - type: rgb_to_bgr

        metrics:
         - name: accuracy@top1
           type: accuracy
           top_k: 1
           reference: 0.86296
         - name: accuracy@top5
           type: accuracy
           top_k: 5
           reference: 0.97746
