models:
- name: octave-se-resnet-50-0.125
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: ImageNet2012
    preprocessing:
    - type: resize
      size: 256
      aspect_ratio_scale: greater
      interpolation: CUBIC
    - type: crop
      size: 224
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
      reference: 0.78706
    - name: accuracy@top5
      type: accuracy
      top_k: 5
      reference: 0.9409
