models:
  - name: pointrend-resnet50-fpn-pytorch

    launchers:
      - framework: dlsdk
        adapter:
          type: mask_rcnn
          classes_out: labels
          boxes_out: boxes
          raw_masks_out: masks

    datasets:
      - name: COCO2017_mask_rcnn_80cl

        preprocessing:
          - type: resize
            dst_width: 1344
            dst_height: 800
            aspect_ratio_scale: fit_to_window

          - type: padding
            dst_width: 1344
            dst_height: 800
            pad_type: right_bottom
            use_numpy: True

        metrics:
          - name: AP@masks
            type: coco_orig_segm_precision
            reference: 0.375373

          - name: AP@boxes
            type: coco_orig_precision
            reference: 0.401066
