models:
  - name: rcan
    launchers:
      - framework: dlsdk
        adapter:
          type: super_resolution
          std: 1
    datasets:
      - name: DIV2K_bicubic_x2
        preprocessing:
          - type: corner_crop
            dst_width: 640
            dst_height: 360
        postprocessing:
          - type: corner_crop_image
            dst_width: 1280
            dst_height: 720
            apply_to: annotation
        metrics:
          - type: psnr
            presenter: print_vector
            reference:
              mean: 34.890962
              std: 5.179973
