models:
  - name: resnet-34-pytorch

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        reader: pillow_imread

        preprocessing:
          - type: bgr_to_rgb

          - type: resize
            size: 256
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BILINEAR
          - type: crop
            size: 224
            use_pillow: True
        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.733
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.9142
