models:
  - name: roberta-base-mrpc
    launchers:
      - framework: dlsdk
        allow_reshape_input: True
        adapter:
          type: bert_classification
          num_classes: 2
        inputs:
          - name: "input_ids"
            type: INPUT
            value: "input_ids"
    datasets:
      - name: GLUE_MRPC_roberta
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
        metrics:
          - type: accuracy
            reference: 0.683824
          - type: classification_f1-score
            pos_label: 1
            reference: 0.812227
