models:
  - name: shufflenet
    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: ImageNet2012
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 0.6511
          - name: accuracy@top5
            type: accuracy
            top_k: 5
            reference: 0.85972
