models:
- name: single-image-super-resolution-1032
  launchers:
  - framework: dlsdk
    adapter:
      type: super_resolution
      reverse_channels: true
    inputs:
    - name: '0'
      type: INPUT
      value: .*lr_x4*.png
    - name: '1'
      type: INPUT
      value: .*upsample_x4*.png
  datasets:
  - name: DIV2K_1920x1080_upsample_x4

    metrics:
    - type: psnr
      scale_border: 4
      presenter: print_vector
      reference:
        mean: 29.29
