models:
  - name: squeezenet1-1

    launchers:
      - framework: opencv
        device: CPU
        tags:
          - FP32
        model:   public/squeezenet1.1/squeezenet1.1.prototxt
        weights: public/squeezenet1.1/squeezenet1.1.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 227, 227
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP32
        backend: OCV
        model:   public/squeezenet1.1/squeezenet1.1.prototxt
        weights: public/squeezenet1.1/squeezenet1.1.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 227, 227
        adapter: classification

      - framework: opencv
        device: GPU
        tags:
          - FP16
        backend: OCV
        model:   public/squeezenet1.1/squeezenet1.1.prototxt
        weights: public/squeezenet1.1/squeezenet1.1.caffemodel
        inputs:
          - name: "data"
            type: INPUT
            shape: 3, 227, 227
        adapter: classification

    datasets:
      - name: ImageNet2012
        data_source: ImageNet

        preprocessing:
          - type: resize
            size: 256

          - type: crop
            size: 227

          - type: normalization
            mean: 104, 117, 123

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
