models:
- name: ssd-resnet34-1200
  launchers:
  - framework: dlsdk
    adapter:
      type: ssd_onnx
      scores_out: .*scores.*
      labels_out: .*labels.*
      bboxes_out: .*bboxes.*
  datasets:
  - name: COCO2017_detection_80cl_bkgr
    reader: pillow_imread
    preprocessing:
    - type: rgb_to_bgr
    - type: resize
      size: 1200
      use_pillow: true
      interpolation: BILINEAR
    postprocessing:
    - type: resize_prediction_boxes
    metrics:
    - type: map
      integral: 11point
      ignore_difficult: true
      presenter: print_scalar
      reference: 0.392816
    - type: coco_precision
      reference: 0.207198
    - type: coco_orig_precision
      reference: 0.198346
