models:
    - name: tedlium_dnn4_smbr
      launchers:
        - framework: dlsdk
          adapter:
            type: kaldi_latgen_faster_mapped
            words_file: tedlium_dnn4/words.txt
            fst_file: tedlium_dnn4/HCLG.fst
            transition_model_file: tedlium_dnn4/final.mdl
            beam: 13
            lattice_beam: 8
            acoustic_score: 0.1
            allow_partial: True
            min_active: 200
            max_active: 7000
            inverse_acoustic_scale: 11.0
          reset_memory_state: true
          device_config:
            GNA:
              GNA_SCALE_FACTOR: "2733.54"
      datasets:
          - name: kaldi_tedlium_dnn4_feats
            metrics:
                - type: wer
                  abs_threshold: 0.09
                  rel_threshold: 0.00001
                  reference: 0.135577
                - type: ser
                  rel_threshold: 0.00001
                  reference: 0.812121

