models:
  - name: time-series-forecasting-electricity-0001
    launchers:
      - framework: dlsdk
        inputs:
          - name: timestamps
            type: INPUT
            layout: NHWC
        adapter:
          type: quantiles_predictor
          output_name: quantiles
          quantiles:
            0.5: 1
            0.9: 2

    datasets:
      - name: Electricity
        postprocessing:
          - type: time_series_denormalize
        metrics:
          - type: normalised_quantile_loss
            presenter: print_vector
            reference:
              0.5: 0.056
              0.9: 0.028
