models:
  - name: ultra-lightweight-face-detection-slim-320

    launchers:
      - framework: dlsdk
        adapter:
          type: ultra_lightweight_face_detection
          boxes_out: "boxes"
          scores_out: "scores"

    datasets:
      - name: WiderFace_label_1

        preprocessing:
          - type: resize
            dst_width: 320
            dst_height: 240

        postprocessing:
          - type: nms
            overlap: 0.5
            include_boundaries: False
          - type: resize_prediction_boxes
          - type: filter
            apply_to: annotation
            height_range: 100
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            reference: 0.8332
