models:
  - name: yolo-tiny-v3
    launchers:
      - framework: dlsdk
        adapter:
          type: yolo_v3
          anchors: tiny_yolo_v3
          num: 3
          coords: 4
          classes: 80
          threshold: 0.001
          anchor_masks: [[3,4,5],[0,1,2]]
          outputs:
            - detector/yolo-v3-tiny/Conv_9/BiasAdd/YoloRegion
            - detector/yolo-v3-tiny/Conv_12/BiasAdd/YoloRegion
    datasets:
      - name:  COCO2017_detection_80cl
        preprocessing:
          - type: resize
            size: 416
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: true
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
            reference: 0.221304
          - type: coco_precision
            max_detections: 100
            threshold: 0.5
            reference: 0.214972
