models:
  - name: yolo-v3

    launchers:
      - framework: dlsdk
        adapter:
          type: yolo_v3
          anchors: yolo_v3
          num: 3
          coords: 4
          classes: 80
          threshold: 0.001
          anchor_masks: [[6,7,8],[3,4,5],[0,1,2]]
          outputs:
            - layer83-yolo
            - layer95-yolo
            - layer107-yolo

    datasets:
      - name: COCO2017_detection_80cl
        preprocessing:
          - type: resize
            size: 416
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: coco_precision
            max_detections: 100
            threshold: .5
            reference: 0.689713
